#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@parentcontrol[-1]
	add ucitrack parentcontrol
	set ucitrack.@parentcontrol[-1].init=parentcontrol
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
