# Copyright (C) 2008-2019 Jerrykuku
# Copyright (C) 2019-2022 sirpdboy
# http://www.github.com/sirpdboy/luci-theme-JituTiktok
# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=JituTiktok Theme

LUCI_DEPENDS:=
PKG_VERSION:=20220304
PKG_RELEASE:=1

include ../../luci.mk
# call BuildPackage - OpenWrt buildroot signature
