# Copyright (C) 2008-2019 Jerrykuku
# Copyright (C) 2019-2022 sirpdboy
# http://www.github.com/sirpdboy/luci-theme-tiktok
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=tiktok Theme
LUCI_DEPENDS:=
PKG_VERSION:=1.0.0
PKG_RELEASE:=20220304

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
