# Copyright (C) 2008-2019 Jerrykuku
# Copyright (C) 2019-2022 sirpdboy
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Argon jitu Mod Theme
LUCI_DEPENDS:=
PKG_VERSION:=1.6
PKG_RELEASE:=20220301

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
