#!/bin/sh /etc/rc.common
# Copyright (C) 2017 lean <coolsnowwolf@gmail.com>

START=99

start() {
	rfc=4096
	cc=$(grep -c processor /proc/cpuinfo)
	rsfe=$(echo $cc*$rfc | bc)
	sysctl -w net.core.rps_sock_flow_entries=$rsfe >/dev/null
	for fileRps in $(ls /sys/class/net/eth*/queues/rx-*/rps_cpus)
	do
		echo $cc > $fileRps
	done
	
	for fileRfc in $(ls /sys/class/net/eth*/queues/rx-*/rps_flow_cnt)
	do
		echo "$rfc" > "$fileRfc"
	done
	
	uci set network.@globals[0].packet_steering="1"
	uci commit network
	g=$(dmesg | grep 'DMI:' | awk -F ', B' '{print $1 }' | awk -F ':' '{print $2 }')

	[ -d /tmp/sysinfo ] || mkdir -p /tmp/sysinfo
	echo $g > /tmp/sysinfo/model

	for i in $(ip address | awk -F ': ' '/eth[0-9]+/ {print $2}'  | awk -F '@' {'print $1'} | awk '{ if ( length($0) <=7 ) print $0}' | xargs)
	do
		{
			ethtool -K "$i" rx-checksum on
			ethtool -K "$i" tx-checksum-ip-generic on || {
				ethtool -K "$i" tx-checksum-ipv4 on
				ethtool -K "$i" tx-checksum-ipv6 on
			}
			ethtool -K "$i" tx-scatter-gather on
			ethtool -K "$i" gso on
			ethtool -K "$i" tso on
			ethtool -K "$i" ufo on
		}
	done

	[ -f /etc/index.htm ] && mv /etc/index.htm /usr/lib/lua/luci/view/admin_status/index.htm
} >"/dev/null" 2>&1
