#!/bin/sh

. /etc/openwrt_release

cpu_arch="$(awk -F ': ' '/model name/ {print $2}' "/proc/cpuinfo" | head -n1)"
[ -n "${cpu_arch}" ] || cpu_arch="ARMv8 Processor"

case "$DISTRIB_TARGET" in
"x86"/*)
	cpu_cores="$(grep "core id" "/proc/cpuinfo" | sort -u | wc -l)核 $(grep -c "processor" "/proc/cpuinfo")线程" ;;
*)
	cpu_cores="$(grep -c "processor" "/proc/cpuinfo")核";;
esac

	echo -n "${cpu_arch} x ${cpu_cores}"
