#!/bin/sh
. /etc/openwrt_release
CPUINFO_PATH="/proc/cpuinfo"
CPUFREQ_PATH="/sys/devices/system/cpu/cpufreq"

case "$DISTRIB_TARGET" in
"bcm27xx"/*)
	cpu_freq="$( $(vcgencmd measure_clock arm | awk -F '=' '{print $2}') / 1000000  |awk -F '.' '{print $1}' ) )Mhz" ;;
"bcm53xx"/*)
	cpu_freq="$(nvram get clkfreq | awk -F ',' '{print $1}')MHz" ;;
"mvebu"/*)
	cpu_freq="$(awk -F ': ' '/BogoMIPS/ {print $2}' "$CPUINFO_PATH" | head -n1)MHz" ;;
"x86"/*)
	cpu_freq="$(awk -F ': ' '/MHz/ {print $2}' '/proc/cpuinfo' | head -n1  |awk -F '.' '{print $1}')MHz" ;;
*)
	[ ! -e "$CPUFREQ_PATH/policy0/cpuinfo_cur_freq" ] || cpu_freq="$(awk '{printf("%.fMHz", $0 / 1000)}' "$CPUFREQ_PATH/policy0/cpuinfo_cur_freq")"
	[ ! -e "$CPUFREQ_PATH/policy4/cpuinfo_cur_freq" ] || big_cpu_freq="$(awk '{printf("%.fMHz ", $0 / 1000)}' "$CPUFREQ_PATH/policy4/cpuinfo_cur_freq")"
	;;
esac

if grep -Eq "ipq|mt7622" "/etc/openwrt_release" ; then
	echo -n "${cpu_freq}"
else
	echo -n "${big_cpu_freq}${cpu_freq}"
fi
