#!/bin/sh
[ ! -d /tmp/state ] && mkdir -p /tmp/state 2>/dev/null
sed -i '/_orig_ifname/d' /etc/config/network
echo -n "[" > /tmp/state/ethinfo

a=$(ip address | awk -F ': ' '/eth[0-9]+/ {print $2}' | awk -F '@' {'print $1'})
b=$(echo "$a" | wc -l)
for i in $(seq 1 $b)
do
        c="$(echo "$a" | sed -n ${i}p)" 
	h=$(echo '{"face":' )
	d=$(ethtool $c)
	face=$(uci show network | grep "$c" | head -n1 |awk -F '.'  '{print $2}' )
	[ "x$face" = "x" ] && continue
	m=$(ifconfig | grep "$c" | head -n1 | awk -F 'HWaddr ' '{print $2}')
	e=$(echo "$d" | grep "Link detected" | awk -F: '{printf $2}' | sed 's/^[ \t]*//g')
	[ $e = yes ] && l=1 || l=0
	f=$(echo "$d" | grep "Speed" | awk -F: '{printf $2}' | sed 's/^[ \t]*//g' | tr -d "Unknown!")
	[ -z "$f" ] && f=" 10Mb/s "
	g=$(echo "$d" | grep "Duplex" | awk -F: '{printf $2}' | sed 's/^[ \t]*//g')
	[ "$g" == "Full" ] && x=1 || x=0
	echo -n "$h \"$face[$c]\", \"status\": $l, \"duplex\": $x, \"speed\": \"$f\", \"mac\": \"$m\"}," >> /tmp/state/ethinfo
done

sed -i 's/.$//' /tmp/state/ethinfo

echo -n "]" >> /tmp/state/ethinfo

cat /tmp/state/ethinfo
