#!/bin/sh
[ "$1" = check ] || exit 1
NAME=bypass

log(){
	 echo "$(date +'%Y-%m-%d %H:%M:%S') By Rules     : $*" >> /tmp/$NAME.log
}

while ! curl -so /dev/null -m 3 www.baidu.com;do
	log "Çë¼ì²éÍøÂç..."
	sleep 2
done
/etc/init.d/$NAME start &