#!/bin/sh
[ "$1" = --First ] && A=Y || A=N
[ -f /var/lock/bypass.lock -a $A = N ] && exit 1
LOCK=/var/lock/bypass-update.lock
[ -f $LOCK ] && exit 1
touch $LOCK
DIR=/usr/share/bypass
TMP=/tmp/bypass
T_FILE=/etc/bypass
log(){
	[ $A = N ] && echo "$(date +'%Y-%m-%d %H:%M:%S') $*" >> /tmp/bypass.log
}

if [ $A = Y ];then
	mkdir -p $TMP
	while ! B=$(curl -Lfsm 9 https://cdn.jsdelivr.net/gh/sirpdboy/iplist/ip/China_IPv4List);do
		sleep 2
	done
else
	B=$(curl -Lfsm 9 https://cdn.jsdelivr.net/gh/sirpdboy/iplist/ip/China_IPv4List || curl -Lfsm 9 https://raw.githubusercontent.com/sirpdboy/iplist/ip/China_IPv4List)
fi
[ -n "$B" ] && echo "$B" | base64 -d > /tmp/china.txt

if ! cmp -s /tmp/china.txt $T_FILE/china.txt;then
	log "By Update  : Update China IP List"
	cp -f /tmp/china.txt $TMP/china.txt
	cp -f /tmp/china.txt $T_FILE/china.txt
	[ $A = N ] && ipset list china_v4 >/dev/null 2>&1 && $DIR/chinaipset
else
	log "By Update  : China IPv4 List is up to date"
fi

C=$(uci -q get bypass.@global[0].run_mode)

if [ "$C" = router ];then
	if [ $A = Y ];then
		mkdir -p $TMP
		while ! D=$(curl -Lfsm 9 https://cdn.jsdelivr.net/gh/sirpdboy/iplist/ip/China_IPv6List);do
			sleep 2
		done
	else
		D=$(curl -Lfsm 9 https://cdn.jsdelivr.net/gh/sirpdboy/iplist/ip/China_IPv6List || curl -Lfsm 9 https://raw.githubusercontent.com/sirpdboy/iplist/main/ip/China_IPv6List)
	fi
	[ -n "$D" ] && echo "$D" | base64 -d > /tmp/china_v6.txt

	if ! cmp -s /tmp/china_v6.txt $T_FILE/china_v6.txt;then
		log "By Update  : Update China IPv6 List"
		cp -f /tmp/china_v6.txt $TMP/china_v6.txt 
		cp -f /tmp/china_v6.txt $T_FILE/china_v6.txt
		[ $A = N ] && ipset list china_v6 >/dev/null 2>&1 && $DIR/chinaipset v6
	else
		log "By Update  : China IPv6 List is up to date"
	fi
fi

if [ "$C" = gfw -o "$(uci -q get bypass.@global[0].gfw_mode)" = 1 -o ! -s $T_FILE/gfw.list ];then
	if [ $A = Y ];then
		while ! curl -Lfsm 5 -o /tmp/gfw.b64 https://cdn.jsdelivr.net/gh/sirpdboy/iplist/ip/GFW_List;do
			sleep 2
		done
	else
		curl -Lfso /tmp/gfw.b64 https://cdn.jsdelivr.net/gh/sirpdboy/iplist/ip/GFW_List || curl -Lfso /tmp/gfw.b64 https://raw.githubusercontent.com/sirpdboy/iplist/main/ip/GFW_List
	fi
	$DIR/gfw
	if ! cmp -s /tmp/gfwnew.txt $T_FILE/gfw.list;then
		cp -f /tmp/gfwnew.txt $TMP/gfw.list 
		cp -f /tmp/gfwnew.txt $T_FILE/gfw.list
		log "By Update  : Update GFW List"
		[ $A = N ] && /etc/init.d/bypass restart
	else
		log "By Update  : GFW List is up to date"
	fi
fi
rm -f $LOCK /tmp/china*.txt /tmp/gfwnew.txt
[ $A = Y ] && /etc/init.d/bypass restart &
