#!/bin/sh
[ "$1" = --First ] && A=Y || A=N
LOCKU=/var/lock/bypass-update.lock
[ -f $LOCKU ] && exit 1
touch $LOCKU
DIR=/usr/share/bypass
TMP=/tmp/bypass
gfwlist_url=$(uci -q get bypass.@global_rules[0].gfwlist_url)
chnroute_url=$(uci -q get bypass.@global_rules[0].chnroute_url)
chnroute6_url=$(uci -q get bypass.@global_rules[0].chnroute6_url)
log(){
	echo "$(date +'%Y-%m-%d %H:%M:%S') $*" >> /tmp/bypass.log
}
[ ! -d $TMP ] && mkdir -p $TMP 2>/dev/null
	if [ $A = Y ];then
		while !  ( curl -kLfsm 5 -o /tmp/china.txt ${chnroute_url}  || curl -Lfsm 5 -o https://fastly.jsdelivr.net/gh/sirpdboy/iplist@main/all_cn.txt  || curl -kLfsm 3 -o /tmp/china.txt https://supes.top/bypass/all_cn.txt  ||  curl -kLfsm 5 -o /tmp/china.txt https://raw.githubusercontent.com/sirpdboy/iplist/all_cn.txt);do
			sleep 1
		done
	else
		curl -kLfsm 5 -o /tmp/china.txt  ${chnroute_url} || curl -Lfsm 5 -o https://fastly.jsdelivr.net/gh/sirpdboy/iplist@main/all_cn.txt  || curl -kLfsm 3 -o /tmp/china.txt https://supes.top/bypass/all_cn.txt  ||  curl -kLfsm 5 -o /tmp/china.txt https://raw.githubusercontent.com/sirpdboy/iplist/all_cn.txt
	fi
		if ! cmp -s /tmp/china.txt $TMP/china.txt;then
			cp -f /tmp/china.txt $TMP/china.txt
			log "By Update  : Updated China IPv4 List :"  $( cat /tmp/bypass/china.txt | wc -l)
			[ $A = N ] && ipset list china_v4 >/dev/null 2>&1 && $DIR/chinaipset
		else
			log "By Update  : China IPv4 List is up to date :"  $( cat /tmp/bypass/china.txt | wc -l)
		fi
C=$(uci -q get bypass.@global[0].run_mode)
if [ "$C" = router ];then
	if [ $A = Y ];then

		while ! (curl -kLfsm 3 -o /tmp/china_v6.txt ${chnroute6_url} || curl -kLfsm 5 -o https://ispip.clang.cn/all_cn_ipv6.txt || curl -kLfsm 5 -o /tmp/china_v6.txt https://fastly.jsdelivr.net/gh/sirpdboy/iplist@main/all_cn_ipv6.txt);do
			sleep 1
		done
	else
		curl -kLfsm 3 -o /tmp/china_v6.txt ${chnroute6_url} || curl -kLfsm 5 -o https://ispip.clang.cn/all_cn_ipv6.txt || curl -kLfsm 5 -o /tmp/china_v6.txt https://fastly.jsdelivr.net/gh/sirpdboy/iplist@main/all_cn_ipv6.txt
	fi

		if ! cmp -s /tmp/china_v6.txt $TMP/china_v6.txt;then
			cp -f /tmp/china_v6.txt $TMP/china_v6.txt 
			log "By Update  : Updated China IPv6 List :" $( cat /tmp/bypass/china_v6.txt | wc -l)
			[ $A = N ] && ipset list china_v6 >/dev/null 2>&1 && $DIR/chinaipset v6
		else
			log "By Update  : China IPv6 List is up to date :" $( cat /tmp/bypass/china_v6.txt | wc -l)
		fi

fi

if [ "$C" = gfw -o "$(uci -q get bypass.@global[0].gfw_mode)" = 1 ];then
	if [ $A = Y ];then
		while ! (curl -kLfsm 5 -o /tmp/gfw.b64 ${gfwlist_url} || curl -Lfsm 5 -o https://fastly.jsdelivr.net/gh/sirpdboy/iplist@main/gfwlist.txt  ||  curl -kLfsm 3 -o /tmp/gfw.b64 https://supes.top/bypass/gfwlist.txt || curl -kLfsm 5 -o /tmp/gfw.b64 https://fastly.jsdelivr.net/gh/YW5vbnltb3Vz/domain-list-community@release/gfwlist.txt   );do
			sleep 2
		done
	else
		curl -kLfsm 5  -o /tmp/gfw.b64 ${gfwlist_url}  || curl -Lfsm 5 -o https://fastly.jsdelivr.net/gh/sirpdboy/iplist@main/gfwlist.txt || curl -kLfsm 3 -o /tmp/gfw.b64 https://supes.top/bypass/gfwlist.txt ||  curl -Lfso /tmp/gfw.b64 https://fastly.jsdelivr.net/gh/YW5vbnltb3Vz/domain-list-community@release/gfwlist.txt  
	fi
	$DIR/gfw
	if ! cmp -s /tmp/gfwnew.txt  $TMP/gfw.list ;then
			cp -f /tmp/gfwnew.txt $TMP/gfw.list 
			log "By Update  : Updated GFW List :" $( cat /tmp/bypass/gfw.list | wc -l)
			[ $A = N ] && /etc/init.d/bypass restart
	else
			log "By Update  : GFW List is up to date :" $( cat /tmp/bypass/gfw.list | wc -l)
	fi

fi
rm -f $LOCKU /tmp/china*.txt /tmp/gfwnew.txt /tmp/gfw.b64

[ $A = Y ] && /etc/init.d/bypass start &
