#!/bin/sh

# Copyright (C) 2015 OpenWrt.org

# 0 yes blockdevice handles this - 1 no it is not there
blkdev=`dirname $DEVPATH`
basename=`basename $blkdev`
device=`basename $DEVPATH`
skip=`block info | grep -vE '(f2fs|kernel|squashfs)' | sed 's/\(.*\): .*/\1/' | grep -q $device ; echo $?`
path=$DEVPATH

if [ $basename != "block" ] && [ -z "${device##sd*}" ] && [ $skip -eq 1 ]; then
	mntpnt=$device
	case "$ACTION" in
		add)
			mkdir -p /mnt/$mntpnt
			chmod 777 /mnt/$mntpnt
			if [ `which fdisk` ]; then
				isntfs=`fdisk -l | grep $device | grep NTFS`
				isvfat=`fdisk -l | grep $device | grep FAT`
				isfuse=`lsmod | grep fuse`
				isntfs3g=`which ntfs-3g`
			else
				isntfs=""
				isvfat=""
			fi
			# mount with ntfs-3g if possible, else with default mount
			if [ "$isntfs" -a "$isfuse" -a "$isntfs3g" ]; then
				ntfs-3g /dev/$device /mnt/$mntpnt
			elif [ "$isvfat" ]; then
				mount -o iocharset=utf8 /dev/$device /mnt/$mntpnt
			else
				# Try to be gentle on solid state devices
				mount -o rw,noatime,discard /dev/$device /mnt/$mntpnt
			fi
		

			;;
		remove)
			# Once the device is removed, the /dev entry disappear. We need mountpoint
			mountpoint=`mount |grep /dev/$device | sed 's/.* on \(.*\) type.*/\1/'`
			umount -l $mountpoint
			;;
	esac
fi
