#!/bin/sh

# Copyright (C) 2015 OpenWrt.org

# 0 yes blockdevice handles this - 1 no it is not there
blkdev=`dirname $DEVPATH`
basename=`basename $blkdev`
device=`basename $DEVPATH`
skip=`block info | grep -vE '(f2fs|kernel|squashfs)' | sed 's/\(.*\): .*/\1/' | grep $device `
path=$DEVPATH

if [[ $basename != "block" && -z "${device##sd*}"  && -n "$skip" ]] ; then
	mntpnt=$device
	case "$ACTION" in
		add)
			mkdir -p /mnt/$mntpnt
			chmod 777 /mnt/$mntpnt
			[ `which ntfs3` ]  && isntfs=`block info |  grep -n$device | grep "ntfs" ` || isntfs=""
			# mount with ntfs3 if possible, else with default mount
			[ "$isntfs" ] && mount -t ntfs3 -o iocharset=utf8 /dev/$device /mnt/$mntpnt || mount -o rw,noatime,discard /dev/$device /mnt/$mntpnt

			;;
		remove)
			# Once the device is removed, the /dev entry disappear. We need mountpoint
			mountpoint=`mount |grep /dev/$device | sed 's/.* on \(.*\) type.*/\1/'`
			umount -l $mountpoint
			;;
	esac
fi
